# Generated by Django 4.0.5 on 2022-06-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Celebrity Gist', 'Celebrity Gist')], default='Test', max_length=200),
        ),
    ]
