# Generated by Django 4.0.5 on 2022-06-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_images_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/profile/')),
                ('twitter_url', models.CharField(max_length=250)),
                ('facebook_url', models.CharField(max_length=250)),
                ('instagram_url', models.CharField(max_length=250)),
                ('linkedin_url', models.CharField(max_length=250)),
            ],
        ),
    ]
