# Generated by Django 4.0.4 on 2022-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_profile_bio_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('News', 'News'), ('Sports', 'Sports'), ('Entertainment', 'Entertainment'), ('Celebrity Gist', 'Celebrity Gist'), ('Recipe', 'Recipe'), ('Lifestyle', 'Lifestyle'), ('Featured', 'Featured'), ('Random', 'Random')], default='Test', max_length=200),
        ),
    ]
